name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - run: |
           aws s3 ls
           ls
           pwd
           aws s3 cp index.html s3://github-demo-s3
           
